server:
  appName: keeper-security-service
  port: 8090
  ip: localhost
  endpoint:
    main: api/auth
    user: api/auth/user
    data: api/auth/data
  db:
    port: 5432
    name: postgres
    schema: auth
    user: postgres
    password: postgrespw
  logging:
    level: info
    filePath: ../logs/security/security.log
  jwt:
    header: Authorization
    secret: proselyte
    #expiration: 18000 #5h 300m
    expiration: 900 #15m

