name: security-action-process
env:
  APP_NAME : "keeper_security"
  DIR_NAME: "_docker/core"
  COMPOSE_NAME: "keeper-core-compose.yml"
on: 
  push:
    branches: 
      - main

jobs:
  Keeper-security:
    runs-on: self-hosted
    
    steps:
      - name: PrintAppData
        run : |
          echo "Application name: ${{ env.APP_NAME}}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: 'false'
      - name: Gradle ${{env.APP_NAME}} clean-build
        run : |
          gradle clean build -x test
      - name: Docker ${{env.APP_NAME}} Update
        run : |
          bash ${{env.APP_NAME}}_update.sh
      - name: Docker Compose up
        run : |
          cd /home/ditar/DataDrive/actions-runner/keeper-actions/${{env.DIR_NAME}}
          docker compose -f ${{env.COMPOSE_NAME}} up -d
